apiVersion: v1
kind: ConfigMap
metadata:
  name: sk014-grafana-datasources
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://sk014-prometheus-svc:9090
        isDefault: true
        uid: prometheus
        jsonData:
          timeInterval: 15s
