# ── Persistence Volume Claim for Backend ────────────────────
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sk014-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  # selector:
  #   matchLabels:
  #     release: "stable"
  #   matchExpressions:
  #     - {key: environment, operator: In, values: [dev]}