# ── Ingress ───────────────────────────────────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk014-ingress
  annotations:
    nginx.ingress.kubernetes.io/scheme: "internet-facing"
    nginx.ingress.kubernetes.io/target-type: "ip"
spec:
  ingressClassName: public-nginx
  rules:
    - host: ingress.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sk014-backend-svc
                port: { number: 8080 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sk014-frontend-svc
                port: { number: 80 }